# SWMAL Intro

## Mini Python Demo

### Mini Python/Jupyternotebook demo

Build-in python array and Numpy arrays...

In [1]:
# Magic: reset/clear all vars, or use Notebook menu Restart, Restart & Clear Output..
%reset -f 

# python build-in array
x = [[1, 2, 3], [4, 5, 6]]

# print using print-f-syntax, prefeed againts say print('x = ',x)
print(f"x = {x}")

print("\nOK")

x = [[1, 2, 3], [4, 5, 6]]

OK


In [2]:
# import clause, imports numpy as the name 'np'
import numpy as np

# create a numpy array (notice the 1.0 double)
y = np.array( [[1.0, 2, 3, 4], [10, 20, 30, 42]] )

print(f"y = \n{y}\n")
print(f"y.shape={y.shape},  y.dtype={y.dtype},  y.itemsize={y.itemsize}, ")

print("\nOK")

y = 
[[ 1.  2.  3.  4.]
 [10. 20. 30. 42.]]

y.shape=(2, 4),  y.dtype=float64,  y.itemsize=8, 

OK


In [3]:
print("indexing...like a (m x n) matrix")
print(y[0, 1])  
print(y[0,-1]) # elem 0-from the 'right', strange but pythonic
print(y[0,-2]) # elem 1-from the 'right'

# print a column, but will display as 'row'
print(y[:,1])

print("\nOK")

indexing...like a (m x n) matrix
2.0
4.0
3.0
[ 2. 20.]

OK


#### Matrix multiplication

Just use Numpy as a matrix like class; create a (3 x 4) matrix and do some matrix operations on it... 

<img src='https://itundervisning.ase.au.dk/SWMAL/L01/Figs/matrix.jpg' alt="WARNING: could not get image from server">

(NOTE: do not use `numpy.matrix`, <a href='https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html'>it is unfortunatly depricated.</a>)

In [6]:
x = np.array([ [2, -5, -11 ,0], [-9, 4, 6, 13], [4, 7, 12, -2]])

y = np.transpose(x)

print(f"x={x}\n\nx.shape={x.shape}\ny.shape={y.shape}")

# No direct * oprator in numpy, 
#  x*y will throw ValueError: operands could not be broadcast together with shapes (3,4) (4,3)
#z=x*y

# numpy dot is a typically combo python function; 
#  inner-product if x and y are 1D arrays (vectors)
#  matrix multiplication if x and y are 2D arrays (matrices) 

print(f"\nmatmul syntax 1: via the dot product, np.dot(x, y)=\n{np.dot(x, y)}\n")

# alternatives to .dot:
print(f"matmul syntax 2: np.matmul(x,y)=\n{np.matmul(x, y)}\n")
print(f"matmul syntax 3: x @ y=\n{x @ y}\n")

# the depricated numpy matrix 
mx = np.matrix(x)
my = np.matrix(y)
mz = mx*my;
print(f"matmul syntax 4: (depricated) matrix type mult mx*my=\n{mz}")

print("\nOK")

x=[[  2  -5 -11   0]
 [ -9   4   6  13]
 [  4   7  12  -2]]

x.shape=(3, 4)
y.shape=(4, 3)

matmul syntax 1: via the dot product, np.dot(x, y)=
[[ 150 -104 -159]
 [-104  302   38]
 [-159   38  213]]

matmul syntax 2: np.matmul(x,y)=
[[ 150 -104 -159]
 [-104  302   38]
 [-159   38  213]]

matmul syntax 3: x @ y=
[[ 150 -104 -159]
 [-104  302   38]
 [-159   38  213]]

matmul syntax 4: (depricated) matrix type mult mx*my=
[[ 150 -104 -159]
 [-104  302   38]
 [-159   38  213]]

OK


More about the dot-product combo function from the Numpy documentation

  https://numpy.org/doc/stable/reference/generated/numpy.dot.html

<br>
<i>
Dot product of two arrays. Specifically,

* If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

* If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

* If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

* If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

* If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b [..]
<i>

#### Writing pythonic, robust code

Range-checks and fail-fast...

In [7]:
import sys, traceback

print("Writing pythonic,robust code: range-checks and fail-fast...")

# python do all kinds of range-checks: robust coding
#print(y[:,-5]) # will throw!

print("a pythonic assert..")
assert True==0, "notice the lack of () in python asserts"

print("\nOK")

Writing pythonic,robust code: range-checks and fail-fast...
a pythonic assert..


AssertionError: notice the lack of () in python asserts

In [8]:
def MyTrace(some_exception):
    import sys, traceback
    
    print(f"Cauth exception e: '{some_exception}'\n")
    traceback.print_exc(file=sys.stdout)
    print()

print("A try-catch block..")

try:
    print(y[:,-5])
except IndexError as e:
    MyTrace(e)
    
finally:
    print("Finally executed last no matter what..")
    
print("\nOK")

A try-catch block..
Cauth exception e: 'index -5 is out of bounds for axis 1 with size 3'

Traceback (most recent call last):
  File "C:\Users\Bruger\AppData\Local\Temp\ipykernel_3076\3635128660.py", line 11, in <module>
    print(y[:,-5])
          ~^^^^^^
IndexError: index -5 is out of bounds for axis 1 with size 3

Finally executed last no matter what..

OK


In [ ]:
# This is python, but weird for C/C++/C# aficionados:

try:
    import a_non_existing_lib
except:
    print("Warning: you don not have the 'a_non_existing_lib' library!")

print("\nOK")

## Administration

REVISIONS||
---------||
2019-01-28| CEF, initial. 
2019-08-20| CEF, E19 ITMAL update. 
2019-08-28| CEF, split into more cells.
2020-01-25| CEF, F20 ITMAL update.
2020-08-31| CEF, E20 ITMAL update, fixed typo in y.shape and make gfx links to BB.
2021-02-01| CEF, F21 ITMAL update.
2021-08-02| CEF, update to E21 ITMAL.
2022-01-25| CEF, update to F22 SWMAL.
2022-01-31| CEF, import fix of traceback, elaborated on dot and minor text fixes.
2022-08-30| CEF, minor update to matmul syntax, updated to v1 changes.
2023-08-30| CEF, minor format update to F23.